### ISSUE TITLE
Uncaught TypeError: (0 , _reactRedux.connect) is not a function at ./node_modules/redux-i18n/dist/component/index.js

### ISSUE THREAD

**Issue by yaswanth-potti-digitech** [APSL/redux-i18n#169]
Got this runtime error for the react application redux, redux-i18n

```
Uncaught TypeError: (0 , _reactRedux.connect) is not a function
    at ./node_modules/redux-i18n/dist/component/index.js (component.js:1:1)
    at options.factory (hot module replacement:378:1)
    at __webpack_require__ (Utility.js:125:1)
    at fn (hot module replacement:36:1)
    at ./node_modules/redux-i18n/dist/index.js (index.js:1:1)
    at options.factory (hot module replacement:378:1)
    at __webpack_require__ (Utility.js:125:1)
    at fn (hot module replacement:36:1)
    at ./src/reducers/index.js (excursionTagsReducers.js:12:1)
    at options.factory (hot module replacement:378:1)
    at __webpack_require__ (Utility.js:125:1)
    at fn (hot module replacement:36:1)
    at ./src/store/configureStore.js (themes.js:581:1)
    at options.factory (hot module replacement:378:1)
    at __webpack_require__ (Utility.js:125:1)
    at fn (hot module replacement:36:1)
```
Updated the packages from 

| Package Name           | Old Version | New Version |
|------------------------|-------------|-------------|
| react                          | ^16.13.1    | ^18.2.0     |
| react-dom                 | ^16.13.1    | ^18.2.0     |
| react-ga                      | ^3.0.0      | ^3.3.1      |
| react-idle-timer            | 5.6.2       | 5.7.2       |
| react-image-gallery    | ^1.0.7      | ^1.3.0      |
| react-leaflet                 | ^2.6.3      | ^4.2.1      |
| react-pdf                     | ^5.7.2      | ^7.7.0      |
| react-player                | ^2.9.0      | ^2.14.1     |
| react-redux                 | ^7.2.0      | ^9.1.0      |
| react-router-dom       | ^5.2.0      | ^6.22.1     |
| redux                          | ^4.0.5      | ^5.0.1      |
| redux-i18n                 | ^1.5.19     | ^1.5.26     |
| redux-thunk                | ^2.2.0      | ^3.1.0      |

**Comment by dinfyru** [comment]
No updates?

**Comment by yaswanth-potti-digitech** [comment]
Can someone help me on this..?
