### ISSUE TITLE
Import script giving error

### ISSUE THREAD

**Issue by gautamvij** [APSL/redux-i18n#46]
Hi, 

Extract script was writing the file with name template.pot. While import script was reading `'locales'}/*.po`. After fixing that, I am facing below error.

```[ 'locales/template.pot' ]
****/node_modules/redux-i18n/bin/import_utils.js:11
  const lang = pocontent.headers.language.replace('_', '-')
                                ^

TypeError: Cannot read property 'language' of undefined
    at exports.getTrans (/home/vagrant/www/ray/modules/react-apps/node_modules/redux-i18n/bin/import_utils.js:11:33)
    at /home/vagrant/www/ray/modules/react-apps/node_modules/redux-i18n/bin/i18n_import.js:18:5
    at Array.map (native)
    at glob (/home/vagrant/www/ray/modules/react-apps/node_modules/redux-i18n/bin/i18n_import.js:17:9)
    at f (/home/vagrant/www/ray/modules/react-apps/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/vagrant/www/ray/modules/react-apps/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/home/vagrant/www/ray/modules/react-apps/node_modules/glob/glob.js:197:8)
    at done (/home/vagrant/www/ray/modules/react-apps/node_modules/glob/glob.js:182:14)
```

**Comment by francescarpi** [comment]
Hi,

can you confirm me if your "lang.po" file header is similar to this?:

<pre>
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.11\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
</pre>

Thanks.
